// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Id, IdTableId } from "./tables/Id.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
import { CreatureType, CreatureTypeTableId } from "./tables/CreatureType.sol";
import { CreatureTypeLineage, CreatureTypeLineageTableId } from "./tables/CreatureTypeLineage.sol";
import { CreatureTypeStats, CreatureTypeStatsData, CreatureTypeStatsTableId } from "./tables/CreatureTypeStats.sol";
import { CreatureMutation, CreatureMutationData, CreatureMutationTableId } from "./tables/CreatureMutation.sol";
import { Predation, PredationTableId } from "./tables/Predation.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Balance, BalanceTableId } from "./tables/Balance.sol";
import { TotalSupply, TotalSupplyTableId } from "./tables/TotalSupply.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { Metdata, MetdataData, MetdataTableId } from "./tables/Metdata.sol";
import { Cooldown, CooldownData, CooldownTableId } from "./tables/Cooldown.sol";
