// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Id, IdTableId } from "./tables/Id.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Creature, CreatureTableId } from "./tables/Creature.sol";
import { Diet, DietTableId } from "./tables/Diet.sol";
import { Drop, DropData, DropTableId } from "./tables/Drop.sol";
import { Predation, PredationTableId } from "./tables/Predation.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Mutation, MutationTableId } from "./tables/Mutation.sol";
import { Balance, BalanceTableId } from "./tables/Balance.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { Metdata, MetdataData, MetdataTableId } from "./tables/Metdata.sol";
