// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Token, TokenTableId } from "./tables/Token.sol";
import { Id, IdTableId } from "./tables/Id.sol";
import { Type, TypeTableId } from "./tables/Type.sol";
import { Immutable, ImmutableTableId } from "./tables/Immutable.sol";
import { ModList, ModListTableId } from "./tables/ModList.sol";
import { Orientation, OrientationTableId } from "./tables/Orientation.sol";
import { MoveStat, MoveStatData, MoveStatTableId } from "./tables/MoveStat.sol";
import { Hook, HookTableId } from "./tables/Hook.sol";
import { AttackStat, AttackStatData, AttackStatTableId } from "./tables/AttackStat.sol";
import { Mutation, MutationData, MutationTableId } from "./tables/Mutation.sol";
import { Predation, PredationTableId } from "./tables/Predation.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Balance, BalanceTableId } from "./tables/Balance.sol";
import { TotalSupply, TotalSupplyTableId } from "./tables/TotalSupply.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { Metdata, MetdataData, MetdataTableId } from "./tables/Metdata.sol";
import { Cooldown, CooldownData, CooldownTableId } from "./tables/Cooldown.sol";
import { MoveCommitment, MoveCommitmentTableId } from "./tables/MoveCommitment.sol";
