// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAttackSubSystem {
  function _attack(bytes32 source, bytes32 target) external;

  function _kill(bytes32 source, bytes32 target) external;
}
