// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAttributesSubSystem {
  function _createAndDefineType(
    address owner,
    bytes32 type_,
    uint32 attackDist,
    uint32 attackCD,
    uint32 moveDist,
    uint32 moveCD
  ) external;

  function _defineType(bytes32 type_, uint32 attackDist, uint32 attackCD, uint32 moveDist, uint32 moveCD) external;

  function _createType(address owner, bytes32 type_) external;
}
