// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICollectSystem {
  function collectGold(uint256 seed, bytes32 to) external;

  function collectItem(uint256 seed, bytes32 to) external;
}
