// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICollectSystem {
  function mintItem(bytes32 itemType) external returns (bytes32);

  function collectGold(uint256[] memory seedBlockNumbers, bytes32 to) external;

  function collectItem(uint256[] memory seedBlockNumbers, bytes32 to) external;
}
