// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { OrientationType } from "./../Types.sol";

interface IItemSystem {
  function pickUp(bytes32 entity, bytes32 owner) external;

  function drop(bytes32 entity, bytes32 owner, int128 x, int128 y, OrientationType orientation) external;

  function transfer(bytes32 entity, bytes32 from, bytes32 to) external;
}
