// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMetadataSystem {
  function setName(bytes32 entity, string memory name) external;

  function setDescription(bytes32 entity, string memory description) external;
}
