// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IModSystem {
  function registerHookHandler(bytes32 hookType, bytes32 entityType, address handler) external;

  function registerMod(bytes32 entityType) external;
}
