// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IModSystem {
  function registerHookHandler(bytes32 name, address handler) external;

  function configureHookHandler(bytes32 hookType, bytes32 entityType, address handler) external;

  function createAndDefineType(
    address owner,
    bytes32 type_,
    uint32 attackDist,
    uint32 attackCD,
    uint32 moveDist,
    uint32 moveCD
  ) external;

  function registerMod(bytes32 entityType) external;
}
