// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMoveSubSystem {
  function _move(bytes32 entity, int128 x, int128 y) external;

  function _traverse(bytes32 entity, uint256 directions) external;
}
