// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { OrientationType } from "./../Types.sol";

interface IMoveSystem {
  function move(
    bytes32 entity,
    int128 x,
    int128 y,
    uint256[] memory goldBlockNumbers,
    uint256[] memory itemBlockNumbers
  ) external;

  function moveRelative(
    bytes32 entity,
    int128 xDist,
    int128 yDist,
    uint256[] memory goldBlockNumbers,
    uint256[] memory itemBlockNumbers
  ) external;

  function turn(bytes32 entity, OrientationType orientation) external;
}
