// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPlayerSpawnSystem {
  function spawn(bytes32 type_, int128 x, int128 y) external;
}
