// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IRegisterModSystem {
  function registerMod(bytes32 source, bytes32 target, bytes32 mod) external;
}
