// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IRegisterHookHandlerSystem {
  function registerHookHandler(bytes32 hookType, bytes32 entityType, address handler) external;
}
