// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITriggerSubSystem {
  function _trigger(bytes32 source, bytes32 target) external;
}
