// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IAttackSubSystem } from "./IAttackSubSystem.sol";
import { IAttributesSubSystem } from "./IAttributesSubSystem.sol";
import { IAuthedCooldownSystem } from "./IAuthedCooldownSystem.sol";
import { IAuthedSystem } from "./IAuthedSystem.sol";
import { ICommitMoveSystem } from "./ICommitMoveSystem.sol";
import { IEntityHookSystem } from "./IEntityHookSystem.sol";
import { IMoveSubSystem } from "./IMoveSubSystem.sol";
import { IMoveSystem } from "./IMoveSystem.sol";
import { IRegisterModSystem } from "./IRegisterModSystem.sol";
import { ISpawnSystem } from "./ISpawnSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  IAttackSubSystem,
  IAttributesSubSystem,
  IAuthedCooldownSystem,
  IAuthedSystem,
  ICommitMoveSystem,
  IEntityHookSystem,
  IMoveSubSystem,
  IMoveSystem,
  IRegisterModSystem,
  ISpawnSystem
{

}
